#!/usr/bin/env python3
"""
S121 — NN Y-Label Normalization Fix
=====================================
Problem: neural_net outputs raw activations (~18914) instead of calibrated
         scores (~0.72). Predictions are generated by ranking raw outputs,
         which gives garbage confidence values and may distort ranking.

Root cause: y_train is NOT normalized before training. NN output layer
            has no constraint, so it learns to output on the raw score scale
            (0.0 - 0.2 range per features, but MSE pushes to raw target range).
            With only 54-85 training samples and targets in range [0.05, 0.20],
            small initialization differences cause huge scale divergence.

Fix — TWO files:
  1. train_single_trial.py  — normalize y before training, save y_mean/y_std
                               to checkpoint, inverse-transform before metrics
  2. models/wrappers/neural_net_wrapper.py — load y_mean/y_std from checkpoint,
                                              apply inverse-transform in predict()

Backward compatible: if checkpoint has no y_mean/y_std (old model), predict()
                     returns raw outputs unchanged (same as before).

Files modified:
  - train_single_trial.py
  - models/wrappers/neural_net_wrapper.py

Author: Team Alpha S121
"""

import os
import sys
import shutil
from pathlib import Path

BASE = Path.home() / "distributed_prng_analysis"
os.chdir(BASE)

APPLIED = []
SKIPPED = []
ERRORS = []


def backup(path: Path):
    bak = Path(str(path) + ".pre_s121_ynorm")
    if not bak.exists():
        shutil.copy2(path, bak)
        print(f"  Backed up: {bak.name}")
    return bak


def patch(path: Path, old: str, new: str, label: str):
    content = path.read_text(encoding="utf-8")
    if old not in content:
        if new.strip().split('\n')[0].strip() in content:
            SKIPPED.append(f"{label} — already applied")
            print(f"  SKIP (already applied): {label}")
        else:
            ERRORS.append(f"{label} — anchor not found")
            print(f"  ERROR anchor not found: {label}")
        return False
    if content.count(old) > 1:
        ERRORS.append(f"{label} — anchor not unique ({content.count(old)} matches)")
        print(f"  ERROR not unique: {label}")
        return False
    path.write_text(content.replace(old, new), encoding="utf-8")
    APPLIED.append(label)
    print(f"  APPLIED: {label}")
    return True


# =============================================================================
# FILE 1: train_single_trial.py
# =============================================================================
print("\n=== Patching train_single_trial.py ===")
f1 = BASE / "train_single_trial.py"
backup(f1)

# PATCH 1a: Add y normalization right after X normalization block,
# before "# Convert to tensors"
# Anchor: the exact comment line before tensor conversion
P1A_OLD = """    # Convert to tensors
    X_train_t = torch.FloatTensor(X_train).to(device)
    y_train_t = torch.FloatTensor(y_train).to(device)  # (N,) matches model .squeeze(-1)
    X_val_t = torch.FloatTensor(X_val).to(device)
    y_val_t = torch.FloatTensor(y_val).to(device)      # (N,) matches model .squeeze(-1)"""

P1A_NEW = """    # ── [S121] Y-label normalization ─────────────────────────────────
    # Normalize targets to zero-mean unit-variance before training.
    # Without this, NN output scale diverges wildly (raw scores ~18914
    # instead of calibrated 0.0-1.0 range) because MSE loss with 54-85
    # training samples gives no implicit scale constraint.
    # y_mean/y_std saved to checkpoint → inverse-transform applied in
    # neural_net_wrapper.predict() for correct Step 6 confidence scores.
    y_mean = float(np.mean(y_train))
    y_std = float(np.std(y_train))
    if y_std < 1e-8:
        y_std = 1.0  # Guard: constant target (degenerate — train normally)
    y_train_norm = (y_train - y_mean) / y_std
    y_val_norm = (y_val - y_mean) / y_std
    print(f"[S121] Y normalization: mean={y_mean:.6f} std={y_std:.6f} "
          f"range=[{y_train_norm.min():.3f}, {y_train_norm.max():.3f}]",
          file=sys.stderr)

    # Convert to tensors
    X_train_t = torch.FloatTensor(X_train).to(device)
    y_train_t = torch.FloatTensor(y_train_norm).to(device)  # (N,) normalized
    X_val_t = torch.FloatTensor(X_val).to(device)
    y_val_t = torch.FloatTensor(y_val_norm).to(device)      # (N,) normalized"""

patch(f1, P1A_OLD, P1A_NEW, "train_single_trial P1a: y normalization before tensors")

# PATCH 1b: Inverse-transform preds before computing metrics
# Anchor: "# Final predictions" comment
P1B_OLD = """    # Final predictions
    model.eval()
    with torch.no_grad():
        train_preds = model(X_train_t).cpu().numpy().flatten()
        val_preds = model(X_val_t).cpu().numpy().flatten()
    
    # Metrics
    train_mse = float(np.mean((train_preds - y_train) ** 2))
    val_mse = float(np.mean((val_preds - y_val) ** 2))"""

P1B_NEW = """    # Final predictions
    model.eval()
    with torch.no_grad():
        train_preds_norm = model(X_train_t).cpu().numpy().flatten()
        val_preds_norm = model(X_val_t).cpu().numpy().flatten()

    # [S121] Inverse-transform predictions back to original scale for metrics
    # Metrics must be on original scale so R² is comparable across model types
    train_preds = train_preds_norm * y_std + y_mean
    val_preds = val_preds_norm * y_std + y_mean

    # Metrics
    train_mse = float(np.mean((train_preds - y_train) ** 2))
    val_mse = float(np.mean((val_preds - y_val) ** 2))"""

patch(f1, P1B_OLD, P1B_NEW, "train_single_trial P1b: inverse-transform before metrics")

# PATCH 1c: Save y_mean/y_std into checkpoint dict
P1C_OLD = """        checkpoint_data = {
            'state_dict': state_to_save,
            'feature_count': input_dim,
            'hidden_layers': hidden_layers,
            'dropout': dropout,
            'best_epoch': best_epoch,
            # Category B: normalization + activation metadata for Step 6 portability
            'normalize_features': normalize_features,
            'use_leaky_relu': use_leaky_relu,
        }
        # Team Beta Decision: store mean/scale as arrays, NOT pickled sklearn
        if scaler_mean is not None:
            checkpoint_data['scaler_mean'] = scaler_mean  # numpy array
            checkpoint_data['scaler_scale'] = scaler_scale  # numpy array"""

P1C_NEW = """        checkpoint_data = {
            'state_dict': state_to_save,
            'feature_count': input_dim,
            'hidden_layers': hidden_layers,
            'dropout': dropout,
            'best_epoch': best_epoch,
            # Category B: normalization + activation metadata for Step 6 portability
            'normalize_features': normalize_features,
            'use_leaky_relu': use_leaky_relu,
            # [S121] Y-label normalization params for inverse-transform at inference
            'y_mean': y_mean,
            'y_std': y_std,
        }
        # Team Beta Decision: store mean/scale as arrays, NOT pickled sklearn
        if scaler_mean is not None:
            checkpoint_data['scaler_mean'] = scaler_mean  # numpy array
            checkpoint_data['scaler_scale'] = scaler_scale  # numpy array"""

patch(f1, P1C_OLD, P1C_NEW, "train_single_trial P1c: save y_mean/y_std to checkpoint")

# PATCH 1d: Add y_mean/y_std to return dict
P1D_OLD = """        # [S96A] Checkpoint validation — parent reads this instead of torch.load
        'checkpoint_validated': checkpoint_path is not None,
        'scaler_shape': list(scaler_mean.shape) if scaler_mean is not None else None,
    }"""

P1D_NEW = """        # [S96A] Checkpoint validation — parent reads this instead of torch.load
        'checkpoint_validated': checkpoint_path is not None,
        'scaler_shape': list(scaler_mean.shape) if scaler_mean is not None else None,
        # [S121] Y normalization params for parent to log/validate
        'y_mean': y_mean,
        'y_std': y_std,
    }"""

patch(f1, P1D_OLD, P1D_NEW, "train_single_trial P1d: add y_mean/y_std to return dict")


# =============================================================================
# FILE 2: models/wrappers/neural_net_wrapper.py
# =============================================================================
print("\n=== Patching models/wrappers/neural_net_wrapper.py ===")
f2 = BASE / "models/wrappers/neural_net_wrapper.py"
backup(f2)

# PATCH 2a: Load y_mean/y_std in load() classmethod
P2A_OLD = """        # Load weights
        wrapper.model.load_state_dict(checkpoint.get('state_dict') or checkpoint.get('model_state_dict'))
        wrapper._fitted = True
        
        logger.info(f\"Neural network loaded from {path} (features: {feature_count})\")
        return wrapper"""

P2A_NEW = """        # Load weights
        wrapper.model.load_state_dict(checkpoint.get('state_dict') or checkpoint.get('model_state_dict'))
        wrapper._fitted = True

        # [S121] Restore Y normalization params for inverse-transform in predict()
        # Backward compatible: old checkpoints have no y_mean/y_std → predict() unchanged
        wrapper._y_mean = checkpoint.get('y_mean', None)
        wrapper._y_std = checkpoint.get('y_std', None)
        if wrapper._y_mean is not None:
            logger.info(f"Y normalization loaded: mean={wrapper._y_mean:.6f} std={wrapper._y_std:.6f}")

        logger.info(f"Neural network loaded from {path} (features: {feature_count})")
        return wrapper"""

patch(f2, P2A_OLD, P2A_NEW, "neural_net_wrapper P2a: load y_mean/y_std in load()")

# PATCH 2b: Apply inverse-transform in predict()
P2B_OLD = """        self.model.eval()
        with torch.no_grad():
            X_tensor = torch.FloatTensor(X).to(self.device)
            predictions = self.model(X_tensor).cpu().numpy()
        
        return predictions"""

P2B_NEW = """        self.model.eval()
        with torch.no_grad():
            X_tensor = torch.FloatTensor(X).to(self.device)
            predictions = self.model(X_tensor).cpu().numpy()

        # [S121] Inverse-transform: convert normalized outputs back to original scale
        # Only applied if checkpoint was trained with S121 y-normalization
        # Backward compatible: _y_mean is None for old checkpoints → no-op
        if getattr(self, '_y_mean', None) is not None:
            predictions = predictions * self._y_std + self._y_mean

        return predictions"""

patch(f2, P2B_OLD, P2B_NEW, "neural_net_wrapper P2b: inverse-transform in predict()")

# PATCH 2c: Initialize _y_mean/_y_std to None in __init__ for safety
# Find __init__ and add defaults after self._fitted = False
P2C_OLD = """        self._fitted = False"""

# Only patch the FIRST occurrence (NeuralNetWrapper.__init__, not SurvivorQualityNet)
content = f2.read_text(encoding="utf-8")
# Find the NeuralNetWrapper class first, then its __init__
idx_class = content.find("class NeuralNetWrapper")
if idx_class == -1:
    ERRORS.append("neural_net_wrapper P2c: NeuralNetWrapper class not found")
    print("  ERROR: NeuralNetWrapper class not found")
else:
    idx_fitted = content.find("        self._fitted = False", idx_class)
    if idx_fitted == -1:
        ERRORS.append("neural_net_wrapper P2c: self._fitted = False not found in NeuralNetWrapper")
        print("  ERROR: self._fitted = False not found")
    else:
        old_block = "        self._fitted = False"
        new_block = """        self._fitted = False
        self._y_mean = None   # [S121] Y normalization — set by load()
        self._y_std = None    # [S121] Y normalization — set by load()"""
        # Only replace the first occurrence after NeuralNetWrapper class definition
        new_content = content[:idx_fitted] + new_block + content[idx_fitted + len(old_block):]
        f2.write_text(new_content, encoding="utf-8")
        APPLIED.append("neural_net_wrapper P2c: init _y_mean/_y_std to None")
        print("  APPLIED: neural_net_wrapper P2c: init _y_mean/_y_std to None")


# =============================================================================
# Verification
# =============================================================================
print("\n=== Verification ===")
f1_content = f1.read_text()
f2_content = f2.read_text()

checks = [
    ("train_single_trial: y_mean computed",   "y_mean = float(np.mean(y_train))" in f1_content),
    ("train_single_trial: y_std computed",    "y_std = float(np.std(y_train))" in f1_content),
    ("train_single_trial: y_train_norm used", "y_train_norm" in f1_content),
    ("train_single_trial: inverse-transform", "train_preds = train_preds_norm * y_std + y_mean" in f1_content),
    ("train_single_trial: checkpoint saves y_mean", "'y_mean': y_mean," in f1_content),
    ("train_single_trial: return includes y_mean",  "'y_mean': y_mean," in f1_content),
    ("neural_net_wrapper: load restores y_mean",    "wrapper._y_mean = checkpoint.get('y_mean', None)" in f2_content),
    ("neural_net_wrapper: predict inverse-transform", "predictions = predictions * self._y_std + self._y_mean" in f2_content),
    ("neural_net_wrapper: _y_mean init",            "self._y_mean = None" in f2_content),
]

all_ok = True
for label, ok in checks:
    status = "✅" if ok else "❌"
    print(f"  {status} {label}")
    if not ok:
        all_ok = False


# =============================================================================
# Summary
# =============================================================================
print("\n=== Summary ===")
print(f"Applied:  {len(APPLIED)}")
for a in APPLIED:
    print(f"  ✅ {a}")
if SKIPPED:
    print(f"Skipped:  {len(SKIPPED)}")
    for s in SKIPPED:
        print(f"  ⏭  {s}")
if ERRORS:
    print(f"Errors:   {len(ERRORS)}")
    for e in ERRORS:
        print(f"  ❌ {e}")

if ERRORS:
    print("\n⚠️  ERRORS found — do NOT commit until resolved.")
    sys.exit(1)
elif all_ok:
    print("\n✅ All patches applied and verified.")
    print("\nNext steps:")
    print("  1. python3 apply_s121_y_norm.py   (this script)")
    print("  2. Quick smoke test:")
    print("     PYTHONPATH=. python3 -c \"")
    print("       from models.wrappers.neural_net_wrapper import NeuralNetWrapper")
    print("       import numpy as np")
    print("       w = NeuralNetWrapper.__new__(NeuralNetWrapper)")
    print("       w._y_mean = 0.1; w._y_std = 0.05; w._fitted = False")
    print("       print('Wrapper init OK')\"")
    print("  3. Run Step 5-6 smoke:")
    print("     PYTHONPATH=. python3 agents/watcher_agent.py \\")
    print("       --run-pipeline --start-step 5 --end-step 6 \\")
    print("       --params '{\"trials\": 3, \"compare_models\": false}'")
    print("  4. Verify scores are in 0.0-1.0 range (not ~18914)")
    print("  5. git add train_single_trial.py models/wrappers/neural_net_wrapper.py")
    print("     git commit -m 'fix(S121): NN y-label normalization'")
    print("     git push origin main && git push public main")
else:
    print("\n⚠️  Verification incomplete — check above.")
    sys.exit(1)
